services:
  db:
    image: postgres:17
    restart: always
    env_file:
      - .env
    volumes:
      - postges_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web-app:
    build:
      context: .
    ports:
      - "8080:8000"
    depends_on:
      - db
    env_file:
      - .env
    command: >
      sh -c "python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"

volumes:
  postges_data: